### ISSUE TITLE
Support HTTPS server

### ISSUE THREAD

**Issue by mpgn** [Den1al/JSShell#18]
As you know, you cannot load an external javascript content from an HTTP server to an HTTPS server.

https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content

> If your website delivers HTTPS pages, all active mixed content delivered via HTTP on this pages will be blocked by default.

Any plan to support HTTPS ?

**Comment by Den1al** [comment]
Yup, I'm currently working on that feature, I will be presenting this project at Blackhat Arsenal this summer, I hope this feature will be done by then.

**Comment by mpgn** [comment]
On my side I manage to do it using __adhoc__ from flask **app.run(ssl_context='adhoc')** on the web server https://github.com/Den1al/JSShell/blob/master/web/__init__.py#L31
Then I set the URL in the config.json to https://ip:port ;)

Of  course this is self-signed certificate but it was enough for me !

**Comment by Den1al** [comment]
@mpgn, Im happy to announce the tool now supports TLS!
