### ISSUE TITLE
JSShell not work property

### ISSUE THREAD

**Issue by enfermerojose2005** [Den1al/JSShell#9]
When I run python3.5 shell.py I recieve this from terminal 

File "shell.py", line 161
SyntaxError: Non-ASCII character '\xe2' in file shell.py on line 162, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Help Please

**Comment by Den1al** [comment]
It seems you're having problems with printing the welcome string. I've wrapped that code in a `try/except` block to avoid that. Thanks for the input, you can look for further details at the #10  .

Please confirm that the issue was indeed fixed for you.

**Comment by enfermerojose2005** [comment]
I donot understand what did mean about i steel with thesame bug

**Comment by Den1al** [comment]
Did you `git pull` / downloaded the latest version?

**Comment by enfermerojose2005** [comment]
Yes i just did git clone https://github.com/Den1al/JSShell

**Comment by enfermerojose2005** [comment]
As usually

**Comment by enfermerojose2005** [comment]
later python ru.py ........... on another terminal shell.py  and appears the bugs as always

**Comment by enfermerojose2005** [comment]
Sorry run.py after that shell.py i another terminal

**Comment by Den1al** [comment]
I'm sorry, I can't quite understand, mind explaining your issue?
